package healthcaresystemapplication;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DanielMedina
 */
public class HealthcareSystemMainMenuGUI extends javax.swing.JFrame {

    /**
     * Creates new form HealthcareSystemMainMenu
     */
    public HealthcareSystemMainMenuGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        payments_btn = new javax.swing.JButton();
        M_Appoint = new javax.swing.JButton();
        Mod_Appoint = new javax.swing.JButton();
        C_Appoint = new javax.swing.JButton();
        access_record_btn = new javax.swing.JButton();
        sign_out_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        payments_btn.setText("Payments");
        payments_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payments_btnActionPerformed(evt);
            }
        });

        M_Appoint.setText("Make Appointment");
        M_Appoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_AppointActionPerformed(evt);
            }
        });

        Mod_Appoint.setText("Modify Appointment");
        Mod_Appoint.setActionCommand("Modify_Appointment");
        Mod_Appoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mod_AppointActionPerformed(evt);
            }
        });

        C_Appoint.setText("Cancel Appointment");
        C_Appoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_AppointActionPerformed(evt);
            }
        });

        access_record_btn.setText("Access Medical Record");
        access_record_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                access_record_btnActionPerformed(evt);
            }
        });

        sign_out_btn.setText("Sign Out");
        sign_out_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign_out_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(C_Appoint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Mod_Appoint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(M_Appoint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(payments_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(access_record_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(218, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sign_out_btn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(payments_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(M_Appoint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Mod_Appoint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C_Appoint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(access_record_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(sign_out_btn))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void payments_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payments_btnActionPerformed
        // TODO add your handling code here:
        new HealthcareSystemPaymentGUI().setVisible(true);
    }//GEN-LAST:event_payments_btnActionPerformed

    private void M_AppointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_AppointActionPerformed
        // TODO add your handling code here:
         new HealthcareSystem_M_AppointGUI().setVisible(true);
    }//GEN-LAST:event_M_AppointActionPerformed

    private void Mod_AppointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mod_AppointActionPerformed
        // TODO add your handling code here:
        new HealthcareSystem_Mod_AppointGUI1().setVisible(true);
    }//GEN-LAST:event_Mod_AppointActionPerformed

    private void C_AppointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_AppointActionPerformed
        // TODO add your handling code here:
        new HealthcareSystem_Can_AppointGUI1().setVisible(true);
    }//GEN-LAST:event_C_AppointActionPerformed

    private void access_record_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_access_record_btnActionPerformed
        // TODO add your handling code here:
        new AccessMedRec().setVisible(true);
    }//GEN-LAST:event_access_record_btnActionPerformed

    private void sign_out_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sign_out_btnActionPerformed
        // TODO add your handling code here:
        new HealthcareSystemGUI().setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_sign_out_btnActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HealthcareSystemMainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HealthcareSystemMainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HealthcareSystemMainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HealthcareSystemMainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HealthcareSystemMainMenuGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton C_Appoint;
    private javax.swing.JButton M_Appoint;
    private javax.swing.JButton Mod_Appoint;
    private javax.swing.JButton access_record_btn;
    private javax.swing.JButton payments_btn;
    private javax.swing.JButton sign_out_btn;
    // End of variables declaration//GEN-END:variables
}
